FROM tensorflow/tensorflow:2.2.1-gpu-py3
MAINTAINER ncvescera nicolo.vescera@gmail.com

RUN pip install --upgrade pip
RUN pip install numpy
RUN pip install pandas
RUN pip install matplotlib
RUN pip install scipy
RUN pip install keras
RUN pip install -U scikit-learn